### ISSUE TITLE
Error deploying with external database

### ISSUE THREAD

**Issue by paola-barredo** [i2group/analyze-deployment-tooling#37] opened 2024-10-28 17:43 UTC
Hello,
I am following the "i2 Analyze containerized deployment documentation": [https://i2group.github.io/analyze-deployment-tooling/]
I've covered the "Getting Started" section and the first part of the "Creating the configuration development environment", until the first deploy everything worked out fine.
 
After that, I jumped to the "Managing configurations" section, into the "Deploying with an external database". I've followed the instructions to set a **Postgresql 15** as my external database. I've modified the **variables.conf** file, generated the db scripts and ran them against the external db, including the dba user script. Finally, I've created the folder postgres in the directory  **configs/config-name/configuration/secrets/** and created a file **dba_istore_PASSWORD.txt** in which I've included the db password. But when I try to execute the  deploy again. I keep getting the following error:

![image (1)](https://github.com/user-attachments/assets/0b5996a6-dc94-4847-94c4-e9769f4aced0)

 As you can see, my implementation is in the directory **/home/anibalmc/analyze-deployment-tooling**. Before making these changes, the rest of the implementation had been working fine in this directory.
I am working with **i2analyzeMinimal4.4.4** and the **analyze-deployment-tooling-3.0.1**.

**Comment by Oleksandr-Kushchak-i2** [comment] 2024-10-29 08:24
Hi @paola-barredo,

It appears the issue is with the file naming. The file `dba_istore_PASSWORD.txt` was created, but the analyze-deployment-tooling expects it to be named `dba_istore_PASSWORD` without the `.txt` extension. Could you please rename the file accordingly? Let us know if you encounter any further issues.

**Comment by paola-barredo** [comment] 2024-10-31 01:03
Hello @Oleksandr-Kushchak-i2 , thank you for your help! This worked just fine, as you mentioned the problem was the txt extension. Although it recognizes the password file, I still haven't been able to do the full deploy, since know I'm getting the following mistake:
![image](https://github.com/user-attachments/assets/a9987f99-ed87-4a7b-be04-9f21a1a334c5)
 I've double checked the db scripts I ran on my db are correct, and I also installed the extensions for Postgres, except for pg_cron, since my external Postgres lives in a Windows and I'm having trouble installing this last extension. Could this error be due to the missing extension? 
 
 Thanks for your time.

**Comment by Oleksandr-Kushchak-i2** [comment] 2024-11-04 17:06
Hi @paola-barredo,

Could you please run the `deploy` script with an iditional flag `-v`, that should give a verbose output for us to diagnose it further.

**Comment by paola-barredo** [comment] 2024-11-12 23:29
Hello @Oleksandr-Kushchak-i2 , we gave this issue a turn around and ended up using the documention described in [here](https://i2group.github.io/analyze-deployment/index.html ). This worked fine with our laboratory, so we sticked with it. Thank you for your time and attention.
Greetings-

**Comment by Anthony-Johnson-i2** [comment] 2024-11-18 12:15
Thanks for the feedback @paola-barredo. I will close this now you have it sorted. 

Cheers

**Closed by Anthony-Johnson-i2** 2024-11-18 12:15 UTC
